### ISSUE TITLE
ERROR: Cannot combine conflicting options --rdp and --nordp

### ISSUE THREAD

**Issue by drndos** [scottyhardy/docker-wine#73] opened 2020-06-26 11:43 UTC
**Describe the bug**
When running `./docker-wine --rdp` I get error `ERROR: Cannot combine conflicting options --rdp and --nordp`
The problem is that there is no default value for NO_RDP variable

**To Reproduce**
1. `wget https://raw.githubusercontent.com/scottyhardy/docker-wine/master/docker-wine -O docker-wine`
2. `chmod +x docker-wine`
3. `./docker-wine --rdp`
4. See error `ERROR: Cannot combine conflicting options --rdp and --nordp`

**Expected behavior**
Docker container with RDP enabled should be started.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Need to add NO_RDP="no" in the default values

**Comment by scottyhardy** [comment] 2020-06-27 11:53
Hi @drndos 

Thanks for taking the time to report this bug.  I've just pushed a fix to the master branch and tested to confirm the issue is resolved.

**Closed by scottyhardy** 2020-06-27 11:53 UTC
Labels: bug
