### ISSUE TITLE
No audio from Wine

### ISSUE THREAD

**Issue by thomaspreece** [scottyhardy/docker-wine#90] opened 2020-07-31 22:52 UTC
**Describe the bug**
When loading ./docker-wine without using the --as-root flag, the audio in wine is not detected. I can run `./docker-wine pacat -vv /dev/urandom` without issue so the link between Host and Docker pulse is fine, the issue is that Wine isn't detecting pulseaudio.  

**To Reproduce**
1. `./docker-wine winecfg`
2. Audio Tab

**Expected behavior**
pulseaudio is detected and shown in winecfg. Clicking Test Sound results in Sound.

**Screenshots**
Expected:
![screenshot](https://user-images.githubusercontent.com/2067021/89084780-ed642e00-d388-11ea-8623-be87767c87de.png)

Actual:
![screenshot_1](https://user-images.githubusercontent.com/2067021/89084826-f05f1e80-d388-11ea-986d-39b1ef2955bc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 18.04

**Comment by scottyhardy** [comment] 2020-08-03 10:17
Hi @thomaspreece, I've tested this on an Ubuntu 18.04 VM and couldn't reproduce the issue.  Could you please ensure you're using the latest `docker-wine` script and also try removing the persistent volume with `docker volume rm winehome` and see if you're still able to reproduce this problem?

**Comment by scottyhardy** [comment] 2020-08-08 12:41
Closing as I can’t reproduce - feel free to reopen if there’s more relevant info and can be replicated

**Closed by scottyhardy** 2020-08-08 12:41 UTC

**Comment by Egorkin-enabled** [comment] 2025-07-29 21:02
Hello! I have the same issue.

<img width="532" height="605" alt="Image" src="https://github.com/user-attachments/assets/bf127a0a-bc5f-4be2-9c19-b50291e88667" />

I'm using `Debian 12` with `Gnome`. Maybe we're making something wrong with forwarding? As a newbie in Dockers (I've worked with them small amount of time) I may assume that it's `true` for my case...

Here's a commands I've used to run `winecfg`:

```bash
sudo docker run -it   \
    --rm  \
    --hostname="$(hostname)" \
    --env="DISPLAY"   --platform="linux/amd64" \
    --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro"  \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro"   scottyhardy/docker-wine winecfg
```

Also `pacat` doesn't run:

```

```bash
sudo docker run -it   \
    --rm  \
    --hostname="$(hostname)" \
    --env="DISPLAY"   --platform="linux/amd64" \
    --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro"  \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro"   scottyhardy/docker-wine pacat -vv /dev/random
```
```
Opening a playback stream with sample specification 's16le 2ch 44100Hz' and channel map 'front-left,front-right'.
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

But the command `pacat -vv /dev/random` directly at the host works as charm:

```bash
pacat -vv /dev/random
```
```
Opening a playback stream with sample specification 's16le 2ch 44100Hz' and channel map 'front-left,front-right'.
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=352800, prebuf=349276, minreq=3528
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_output.pci-0000_00_1b.0.analog-stereo (index: 56, suspended: no).
Stream started.
^CGot signal, exiting.cy: 2043277 usec.
```

Ah... Charmy noise!.... But not from the docker unfortunately.

I installed this image through `docker pull` command:

```bash
sudo docker pull scottyhardy/docker-wine
```

Maybe this information helps somehow.

I'll also try to find workaround of this problem. 

Anyway, thank you for this image. At least `X11` forwarding working well and this repo shows that it's possible to run `wine` apps using `docker` 's sandbox.

**Comment by Egorkin-enabled** [comment] 2025-07-30 00:33
Oh! I'm sorry! Didn't notice `./docker-wine` script! I'll try to run `wine` through it.
